sudo: required
services: 
  - docker

before_install:
  - docker build -t ekaitz/docker-react -f Dockerfile.dev .

script: 
  - docker run ekaitz/docker-react npm run tes"docker build" requires exactly 1 argument.

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"  
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-950170569551"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"


